# Generated by Django 5.1.1 on 2024-10-02 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_userprofile_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='organization',
        ),
        migrations.AddField(
            model_name='product',
            name='ean',
            field=models.CharField(max_length=13, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
