# Generated by Django 5.1.1 on 2024-10-03 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_product_organization_product_ean_product_sku_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ean',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
